
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JHON
 */
public class Tables extends javax.swing.JFrame {

    /**
     * Creates new form Tables
     */
     int Counter=0;
     DefaultTableModel MD;
    public Tables()
    {
        
       // this.setTitle(FNAME);
       this.setVisible(true);
        initComponents();
        MD=(DefaultTableModel)TBL.getModel();
        MD.setRowCount(0);
       // Counter++;
    }
    
    public void Tables(ArrayList<String> VN ,ArrayList<String> VT,ArrayList<String> MN,ArrayList<String> MT,String FNAME) {
      
       
        
        
         Print(VN,VT,MN,MT,TBL);
         MD.setRowCount(Counter+1);
         TBL.setRowHeight(Counter, 30);
         TBL.getModel().setValueAt(FNAME, Counter,0);
         
         Counter++;

        
    }

    public void Print(ArrayList<String> VN,ArrayList<String> VT,ArrayList<String> MN,ArrayList<String> MT,JTable TBL)
        {
           
        
           
            
            
            
            
            for(int  i=0;i<(VN.size()>=MN.size()? VN.size():MN.size());i++)
                {
                    MD.setRowCount(Counter+1);
                    if(i<VN.size())
                    {
                        TBL.getModel().setValueAt(VN.get(i), Counter,1);
                        TBL.getModel().setValueAt(VT.get(i), Counter, 2);
                    }
                    
                    
                    if(i<MT.size())
                        {
                            TBL.getModel().setValueAt(MN.get(i), Counter,3);
                            TBL.getModel().setValueAt(MT.get(i), Counter, 4);
                        }
                    

                    Counter++;
                }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBL = new javax.swing.JTable();
        PN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Class Name", "Variable Name", "Variable Type", "Method Name", "Method Type"
            }
        ));
        jScrollPane1.setViewportView(TBL);

        PN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PN.setText("SDA Project");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(PN)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PN;
    private javax.swing.JTable TBL;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
